### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by CodEnFisH** [Tencent/flare#12]
./blade build ... gave me the following errors

```
ERROR:root:code` for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/server_dev/.blade_boost/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/server_dev/.blade_boost/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
...
... (similar error for other hashes)
...
Traceback (most recent call last):
  File "/home/server_dev/.blade_boost/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/server_dev/.blade_boost/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/server_dev/repo/flare/thirdparty/blade/blade.zip/__main__.py", line 14, in <module>
  File "/home/server_dev/repo/flare/thirdparty/blade/blade.zip/blade/__init__.py", line 6, in <module>
  File "/home/server_dev/repo/flare/thirdparty/blade/blade.zip/blade/config.py", line 422, in <module>
  File "/home/server_dev/repo/flare/thirdparty/blade/blade.zip/blade/config.py", line 44, in __init__
AttributeError: 'module' object has no attribute 'md5'
```

I though it was my openssl lib being missing, reinstalled but still no luck.

**Comment by chen3feng** [comment]
Should depend on user installed python, TO BE FIXED soo.

**Comment by 0x804d8000** [comment]
`yum install xz-devel openssl-devel && rm -rf ~/.blade_boost` should help. (Assuming CentOS 7 is used. Package names may vary on other Linux distros.)

**Comment by CodEnFisH** [comment]
> `yum install xz-devel openssl-devel && rm -rf ~/.blade_boost` should help. (Assuming CentOS 7 is used. Package names may vary on other Linux distros.)

If you meant liblzma-dev and libopenssl on ubuntu, I had both installed. Don't think the root cause is missing libs.

**Comment by 0x804d8000** [comment]
I couldn't reproduce the error with Ubuntu 20.04 using Docker. Are you using an older version?

Besides, there are some other issues on Ubuntu 20.04, we're still working on it. (see #18 )
